### ISSUE TITLE
UI options selection improvements checklist

### ISSUE THREAD

**Issue by qdread** [qdread/biodiversity-farm2fork#11]
- [x] If map tab is active, we can only show either domestic or foreign, not total. So maybe disable or disappear that if map is active (line 83-88 of app.R)
- [x] Selection of scenario option only visible if map is visible (because the plot and table show all 10 scenarios) (line 89-95 of app.R)
- [x] Log-transformation should adaptively change to the most sensible default (log scale for raw values and non log scale for the relative changes) (line 99-103 of app.R)
- [x] Flow options (goods, land, and taxa) only visible if the corresponding flow type is selected. Both land and taxa should be visible for biodiversity because the values are disaggregated by both land and taxa there. (line 107-127 of app.R)
- [x] the log transform is entirely ignored if normalize == TRUE. Maybe disable it in that case? (line 99-103 of app.R)

**Comment by qdread** [comment]
@khondula fixed all this stuff! yea! 🍹 See #16

**Comment by khondula** [comment]
Now that only onebset of subcategories shows up at once, what do you think about using checkbox input instead of selectinput?

**Comment by qdread** [comment]
Yeah that would actually be fine now I think -- like you're saying, the main reason I made the selectinput instead of checkboxes was to not have three long menus but if only one appears at once that is no longer an issue.

Also I did notice one thing about your pr. Now when you switch between tabs, sometimes the selected options reset. It would be nice to keep the ones that are selected, if still valid. I will make a new issue for you :-D
