### ISSUE TITLE
Table improvements checklist

### ISSUE THREAD

**Issue by qdread** [qdread/biodiversity-farm2fork#9]
- [ ] Improve column labels (include units on Flow) -- or add this info in a caption below the table.
- [ ] Formatting improvements to make table look nicer?
- [ ] right now it's the summed up data but maybe we can also show data by county or country?
- [ ] allow the user to subset the data by county or country in the table, and/or sort it
